### ISSUE TITLE
Exclude Deppbot branches from Travis

### ISSUE THREAD

**Issue by lowjoel** [deppbot/feedback#1]
If you've set up Travis, then this extra config in .travis.yml will ensure that the Deppbot branches aren't built twice (and saves strain on Travis' infrastructure)

``` yml
branches:
  except:
    - /^bundle-update-[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{6}+$/
```

Maybe put this somewhere? If it is already in the docs somewhere I missed it...
